version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ./data:/app/data

  frontend:
    build:
      context: ./client-vite
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend 